{
 "title": "Dropvox JVM",
 "tags": [
  "dropvox",
  "observability"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Heap Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JVM Threads count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (service) (jvm_threads_live_threads)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (service) (process_cpu_usage) * 100",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "RAM Usage by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (service) (jvm_memory_used_bytes)",
     "legendFormat": "{{service}}"
    }
   ]
  }
 ]
}