@startuml download_file_seq
title Download File Sequence

actor "User" as user
participant "API Gateway" as gate
participant "Auth Service" as auth
participant "Metadata Service" as metadata
participant "Redis" as redis
participant "PostgreSQL" as db
participant "MinIO" as s3

note right of user : File successfully downloaded path
user -> gate: GET /files/{id}
gate -> auth: validate JWT
auth --> gate: OK
gate -> metadata: GET file metadata & request presignedURL
metadata -> redis: retrieved cached metadata
metadata -> db: (optional) retrieved metadata if not cached
|||
metadata -> s3: request presignedURL(GET, bucket, key)
s3 --> metadata: presignedURL
metadata --> gate: metadata + presignedURL
gate --> user: metadata + presignedURL
user -> s3: GET {presignedURL}
s3 --> user: file stream

note right of user : TODO File failed to be downloaded path
@enduml