# HTTP server
server.port=8082

# PostgreSQL
db.host=postgres-service
db.port=5432
db.database=dropvox
db.user=user     #Should be defined as env var
db.password=pass #Should be defined as env var
db.pool.maxSize=5

# MinIO / S3
s3.endpoint=http://minio:9000
s3.accessKey=minioadmin
s3.secretKey=minioadmin
s3.bucket=dropvox-files

# Presigned URL expiration (minutes)
presigned.url.expiry.minutes=5
