@dockerApi = http://localhost:8082
@localApi = http://localhost:9082
@api = {{dockerApi}}
@userId = 3b069db6-b46a-4766-96d8-9bee5c5a32be

### 1) Init upload and capture fileId + uploadUrl
POST {{api}}/files/init
Accept: application/json
Content-Type: application/json
X-User-Id: {{userId}}

{
  "filename": "Engine",
  "contentType": "ini",
  "size": 11000
}
> {%
    client.global.set("fileId", response.body.fileId);
    client.global.set("uploadUrl", response.body.uploadUrl);
%}

### 2) Upload content to MinIO using presigned URL (must be PUT)
PUT {{uploadUrl}}
Content-Type: application/octet-stream

< ./Engine.ini

### 3) Mark upload complete in metadata service
POST {{api}}/files/complete/{{fileId}}
Accept: application/json
X-User-Id: {{userId}}

### 4) Verify metadata
GET {{api}}/files/{{fileId}}
Accept: application/json
X-User-Id: {{userId}}

