@dockerApi = http://localhost:8080
@localApi = http://localhost:9080
@api = {{dockerApi}}
@downloadUrl = {{downloadUrl}}

### 1) Init upload and capture fileId + uploadUrl
POST {{api}}/files/init
Accept: application/json
Content-Type: application/json

{
  "filename": "Engine",
  "contentType": "ini",
  "size": 11000
}
> {%
    client.global.set("fileId", response.body.fileId);
    client.global.set("uploadUrl", response.body.uploadUrl);
%}

### 2) Upload content to MinIO using presigned URL (must be PUT)
PUT {{uploadUrl}}
Content-Type: application/octet-stream

< ./Engine.ini

### 3) Request async upload completion (returns 202 Accepted)
POST {{api}}/files/{{fileId}}/completion-request
Accept: application/json

### 4) Poll upload status until it becomes UPLOADED
GET {{api}}/files/{{fileId}}/status
Accept: application/json

### 5) Fetch download metadata
GET {{api}}/files/{{fileId}}
Accept: application/json

> {%
    client.global.set("downloadUrl", response.body.downloadUrl);
%}

### 6) Download uploaded file
GET {{downloadUrl}}
